/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Jan
 */
public class AssetViewer extends Page {

    /**
     * Creates new form AssetViewer
     */
    
    private Integer userID;
    private int AssetID;
        
   
    
    public AssetViewer() {
      //initComponents();
      
      this.setLocationRelativeTo(null);
        
    }

    
    public void SetValues(ResultSet Asset, ResultSet prevOwners, String UserType, String UserName){
        setUsername(UserName);
        setUserType(UserType);

        Vector<String> res = new Vector<String>();

        try{ 
            while (prevOwners.next()) {

                String oFirstname = prevOwners.getString("ofirstname");
                String oLastname = prevOwners.getString("olastname");
                res.add(oFirstname+" "+oLastname);
            }

        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);            
        }

        getListPreviousOwners().setListData(res);       

        try
        {
            Asset.next();
            getLbAssetName().setText((Asset.getString("assetname")));
            getLbAssetID().setText((Asset.getString("assetid")));
            String oFirstname = Asset.getString("ofirstname");
            String oLastname = Asset.getString("olastname");
            getLbOwner().setText(oFirstname+" "+oLastname);
            String cFirstname = Asset.getString("cfirstname");
            String cLastname = Asset.getString("clastname");
            if(cFirstname == null)
                getLbCustodian().setText("N/A");
            else
                getLbCustodian().setText(cFirstname+" "+cLastname);
            getLbType().setText((Asset.getString("assettype")));
            getLbDate().setText(Asset.getString("dateacquired"));
            getLbRetention().setText((Asset.getString("retentionperiod")));
            getLbMaintenance().setText((Asset.getString("mainsched")));
            getLbFinancial().setText((Asset.getString("financialval")));
            getLbConfidentiality().setText((Asset.getString("confidentialityval")));
            getLbAvailability().setText((Asset.getString("availabilityval")));
            getLbIntegrity().setText((Asset.getString("integrityval")));
            getLbClassification().setText((Asset.getString("classification")));
            getLbStorage().setText((Asset.getString("storagelocation")));

            setUserID(Asset.getInt("asset_ownerid"));

            if(res.isEmpty()){
                getLbPreviousOwner().setText("N/A");
            }
            else
                getLbPreviousOwner().setText(res.lastElement());

        }catch(SQLException s){
            System.out.println(s);
        }

        setVisible(true);
        setLocationRelativeTo(null);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

    public String getUserType() {
        return userType;
    }

    public String getUsername() {
        return username;
    }
    
    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    } 
    
    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    } 
    
    
    
    public void setjLabel26(JLabel jLabel26) {
        this.jLabel26 = jLabel26;
    }
    
    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }
    
    public void setjLabel24(JLabel jLabel24) {
        this.jLabel24 = jLabel24;
    }
    
    public void setjLabel22(JLabel jLabel22) {
        this.jLabel22 = jLabel22;
    }
    
    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }
    
    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }
    
    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }
              
    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }
    
    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }
    
    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }
    
    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }
    
    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }
    
    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }
           
    
    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }
    
    
    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }
    
     public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }
    
     public void setEditButton(JButton btnEdit) {
        this.btnEdit = btnEdit;
    }
 
    public void addActionListener(ActionListener listener) {
        btnEdit.addActionListener(listener);
    }
     
     public void setlistPreviousOwners(JList listPreviousOwners) {
        this.listPreviousOwners = listPreviousOwners;
    }
    
     public void set(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }
     
     public void setlbAssetID(JLabel lbAssetID) {
        this.lbAssetID = lbAssetID;
    }
     
     public void setlbAssetName(JLabel lbAssetName) {
        this.lbAssetName = lbAssetName;
    }
     
     public void setlbAvailability(JLabel lbAvailability) {
        this.lbAvailability = lbAvailability;
    }
     
     public void setlbClassification(JLabel lbClassification) {
        this.lbClassification = lbClassification;
    }
     
     public void setlbConfidentiality(JLabel lbConfidentiality) {
        this.lbConfidentiality = lbConfidentiality;
    }
     
     public void setlbCustodian(JLabel lbCustodian) {
        this.lbCustodian = lbCustodian;
    }
     
     public void setlbDate(JLabel lbDate) {
        this.lbDate = lbDate;
    }
     
     public void setlbFinancial(JLabel lbFinancial) {
        this.lbFinancial = lbFinancial;
    }
     
     public void setlbIntegrity(JLabel lbIntegrity) {
        this.lbIntegrity = lbIntegrity;
    }
     
     public void setlbMaintenance(JLabel lbMaintenance) {
        this.lbMaintenance = lbMaintenance;
    }
     
     public void setlbOwner(JLabel lbOwner) {
        this.lbOwner = lbOwner;
    }
     
     public void setlbPreviousOwner(JLabel  lbPreviousOwner) {
        this. lbPreviousOwner =  lbPreviousOwner;
    }
     
     public void setlbRetention(JLabel lbRetention) {
        this.lbRetention = lbRetention;
    }
     
     public void setlbStorage(JLabel lbStorage) {
        this.lbStorage = lbStorage;
    }
     
     public void setlbType(JLabel lbType) {
        this.lbType = lbType;
    }
     

    public JButton getEditButton() {
        return btnEdit;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel22() {
        return jLabel22;
    }

    public JLabel getjLabel24() {
        return jLabel24;
    }

    public JLabel getjLabel26() {
        return jLabel26;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JLabel getLbAssetID() {
        return lbAssetID;
    }

    public JLabel getLbAssetName() {
        return lbAssetName;
    }

    public JLabel getLbAvailability() {
        return lbAvailability;
    }

    public JLabel getLbClassification() {
        return lbClassification;
    }

    public JLabel getLbConfidentiality() {
        return lbConfidentiality;
    }

    public JLabel getLbCustodian() {
        return lbCustodian;
    }

    public JLabel getLbDate() {
        return lbDate;
    }

    public JLabel getLbFinancial() {
        return lbFinancial;
    }

    public JLabel getLbIntegrity() {
        return lbIntegrity;
    }

    public JLabel getLbMaintenance() {
        return lbMaintenance;
    }

    public JLabel getLbOwner() {
        return lbOwner;
    }

    public JLabel getLbPreviousOwner() {
        return lbPreviousOwner;
    }

    public JLabel getLbRetention() {
        return lbRetention;
    }

    public JLabel getLbStorage() {
        return lbStorage;
    }

    public JLabel getLbType() {
        return lbType;
    }

    public JList getListPreviousOwners() {
        return listPreviousOwners;
    }

    public Integer getUserID() {
        return userID;
    }
     
     
     
     
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAssetID;
    private javax.swing.JLabel lbAssetName;
    private javax.swing.JLabel lbAvailability;
    private javax.swing.JLabel lbClassification;
    private javax.swing.JLabel lbConfidentiality;
    private javax.swing.JLabel lbCustodian;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbFinancial;
    private javax.swing.JLabel lbIntegrity;
    private javax.swing.JLabel lbMaintenance;
    private javax.swing.JLabel lbOwner;
    private javax.swing.JLabel lbPreviousOwner;
    private javax.swing.JLabel lbRetention;
    private javax.swing.JLabel lbStorage;
    private javax.swing.JLabel lbType;
    private javax.swing.JList listPreviousOwners;
    // End of variables declaration//GEN-END:variables


	public void setUserID(Integer userID) {
		this.userID = userID;
	}

	public int getAssetID() {
		return AssetID;
	}

	public void setAssetID(int assetID) {
		AssetID = assetID;
	}
}
