/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.LoginMenuHandler;
import View.Builders.AbstractFormBuilder;
import View.Builders.FormDirector;
import View.Builders.MainMenuBuilder;

import javax.swing.*;

/**
 *
 * @author Jan
 * 
 */

public class LoginMenu extends Form {
    

    /**
     * Creates new form Login
     */
    public LoginMenu() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public JButton getBtLogin() {
        return btLogin;
    }

    public void setBtLogin(JButton btLogin) {
        this.btLogin = btLogin;
    }

    public ButtonGroup getBtnGrp() {
        return btnGrp;
    }

    public void setBtnGrp(ButtonGroup btnGrp) {
        this.btnGrp = btnGrp;
    }

    public JButton getBtnRegister() {
        return btnRegister;
    }

    public void setBtnRegister(JButton btnRegister) {
        this.btnRegister = btnRegister;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JLabel getLbError() {
        return lbError;
    }

    public void setLbError(JLabel lbError) {
        this.lbError = lbError;
    }

    public JPasswordField getPfPassword() {
        return pfPassword;
    }

    public void setPfPassword(JPasswordField pfPassword) {
        this.pfPassword = pfPassword;
    }

    public JRadioButton getRbCustodian() {
        return rbCustodian;
    }

    public void setRbCustodian(JRadioButton rbCustodian) {
        this.rbCustodian = rbCustodian;
    }

    public JRadioButton getRbOwner() {
        return rbOwner;
    }

    public void setRbOwner(JRadioButton rbOwner) {
        this.rbOwner = rbOwner;
    }

    public JTextField getTfUsername() {
        return tfUsername;
    }

    public void setTfUsername(JTextField tfUsername) {
        this.tfUsername = tfUsername;
    }
    
    public String getRbGrp(){
        if(rbOwner.isSelected())
            return "Owner";
        else
            return "Custodian";
    }
    
    public String getDecipheredPassword(JPasswordField pf){
        char[] c = pf.getPassword();
        String s = String.valueOf(c);
        return s;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.ButtonGroup btnGrp;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbError;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JRadioButton rbCustodian;
    private javax.swing.JRadioButton rbOwner;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables

    

}
