/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerUtility;

import java.sql.ResultSet;
import java.util.Vector;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;

/**
 *
 * @author Jan
 */
public class MainMenu extends Page {

    /**
     * Creates new form MainMenu
     */
    private String userType;
    private String password;
    private int userID;
    private Vector<String> assetIDs = new Vector<String>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAddActionPerformed


    public JButton getBtAdd() {
        return btAdd;
    }

    public JButton getBtDelete() {
        return btDelete;
    }

    public JButton getBtEdit() {
        return btEdit;
    }

    public JLabel getLbID() {
        return lbID;
    }

    public JLabel getLbName() {
        return lbName;
    }
        

    public String getUserType() {
        return userType;
    }

    public String getPassword() {
        return password;
    }

    public Vector<String> getAssetIDs() {
        return assetIDs;
    }

    public JList getListOfAsset() {
        return listOfAsset;
    }

    public void setListOfAsset(JList listOfAsset) {
        this.listOfAsset = listOfAsset;
    }

    public JButton getBtView() {
        return btView;
    }

    public JButton getBtLogout() {
        return btLogout;
    }

    public JButton getBtRefresh() {
        return btRefresh;
    }

    public int getUserID() {
        return userID;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public JLabel getLbUserType() {
        return lbUserType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setUserID(int userID) {
        this.userID = userID;
    }

    public void setBtAdd(JButton btAdd) {
        this.btAdd = btAdd;
    }

    public void setBtDelete(JButton btDelete) {
        this.btDelete = btDelete;
    }

    public void setBtEdit(JButton btEdit) {
        this.btEdit = btEdit;
    }

    public void setBtLogout(JButton btLogout) {
        this.btLogout = btLogout;
    }

    public void setBtRefresh(JButton btRefresh) {
        this.btRefresh = btRefresh;
    }

    public void setBtView(JButton btView) {
        this.btView = btView;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public void setLbID(JLabel lbID) {
        this.lbID = lbID;
    }

    public void setLbName(JLabel lbName) {
        this.lbName = lbName;
    }

    public void setLbUserType(JLabel lbUserType) {
        this.lbUserType = lbUserType;
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btRefresh;
    private javax.swing.JButton btView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbUserType;
    private javax.swing.JList listOfAsset;
    // End of variables declaration//GEN-END:variables
}
